"""Append additional demo projects (run once)."""
from database import SessionLocal, engine, Base
from models import Project

Base.metadata.create_all(bind=engine)
db = SessionLocal()

MORE = [
    dict(title="Realtime Fraud Detection Engine",
         subtitle="Streaming transaction scoring with sub-100ms latency",
         description="A streaming pipeline that scores transactions for fraud in real time using gradient-boosted models served behind a low-latency API.",
         problem_statement="Batch fraud checks miss fast-moving attacks; teams need scoring within the payment flow.",
         tech_stack=["Python", "Kafka", "FastAPI", "Redis", "React"],
         architectures_used=["Event-driven", "Streaming", "Microservices"],
         libraries_used=["XGBoost", "river", "confluent-kafka", "Recharts"],
         difficulty="Advanced",
         build_plan="## Phase 1\nStand up Kafka + a transaction producer.\n## Phase 2\nTrain an XGBoost scorer; serve via FastAPI.\n## Phase 3\nBuild a live ops dashboard of flagged transactions.",
         ui_components=["Live alerts feed", "Score distribution chart", "Rule editor"],
         repo_inspiration=["feast-dev/feast", "online-ml/river"],
         resume_gap_filled="Demonstrates real-time ML serving and streaming systems.",
         key_features=["Sub-100ms scoring", "Online model updates", "Alert triage UI"],
         learning_outcomes=["Streaming architecture", "Low-latency inference", "Feature stores"],
         tags=["ML/AI", "Real-Time", "Backend", "Security"]),
    dict(title="Multi-Tenant SaaS Billing Platform",
         subtitle="Usage metering, invoicing and Stripe integration",
         description="A billing backbone for SaaS apps: meter usage, aggregate to invoices, and reconcile payments.",
         problem_statement="Rolling your own metering/invoicing is error-prone and hard to audit.",
         tech_stack=["TypeScript", "Node.js", "PostgreSQL", "React"],
         architectures_used=["Multi-tenant", "Event-sourcing"],
         libraries_used=["Prisma", "BullMQ", "Stripe", "TanStack Query"],
         difficulty="Advanced",
         build_plan="## Phase 1\nModel tenants, plans, usage events.\n## Phase 2\nAggregate usage to invoices nightly.\n## Phase 3\nReconcile Stripe webhooks; build an admin console.",
         ui_components=["Usage meters", "Invoice viewer", "Plan editor"],
         repo_inspiration=["lago-money/lago"],
         resume_gap_filled="Shows billing correctness, idempotency and multi-tenancy.",
         key_features=["Usage metering", "Automated invoicing", "Stripe reconciliation"],
         learning_outcomes=["Idempotent webhooks", "Multi-tenant data isolation"],
         tags=["Full-Stack", "Backend", "Payments"]),
    dict(title="Edge IoT Telemetry Hub",
         subtitle="Ingest, downsample and visualize device telemetry",
         description="Collect high-frequency sensor data at the edge, downsample, and stream to a time-series dashboard.",
         problem_statement="Naive telemetry ingestion overwhelms storage and dashboards.",
         tech_stack=["Python", "MQTT", "TimescaleDB", "React"],
         architectures_used=["Edge computing", "Time-series"],
         libraries_used=["paho-mqtt", "asyncpg", "Plotly"],
         difficulty="Intermediate",
         build_plan="## Phase 1\nMQTT broker + simulated devices.\n## Phase 2\nDownsampling worker into TimescaleDB.\n## Phase 3\nLive charts with continuous aggregates.",
         ui_components=["Device map", "Time-series charts", "Alert thresholds"],
         repo_inspiration=["eclipse/mosquitto"],
         resume_gap_filled="Covers time-series modeling and edge ingestion.",
         key_features=["High-frequency ingest", "Continuous aggregates", "Threshold alerts"],
         learning_outcomes=["Time-series DBs", "Downsampling", "MQTT"],
         tags=["Data Engineering", "Real-Time", "DevOps"]),
    dict(title="Semantic Job Matching API",
         subtitle="Embed resumes and postings; rank matches",
         description="A matching service that embeds resumes and job posts into a shared vector space and ranks fits.",
         problem_statement="Keyword matching misses semantically similar skills and roles.",
         tech_stack=["Python", "FastAPI", "pgvector", "React"],
         architectures_used=["Vector search", "Microservices"],
         libraries_used=["sentence-transformers", "pgvector", "FastAPI"],
         difficulty="Intermediate",
         build_plan="## Phase 1\nEmbed documents into pgvector.\n## Phase 2\nRank with cosine similarity + filters.\n## Phase 3\nExplainable match breakdown UI.",
         ui_components=["Match list", "Similarity breakdown", "Filter panel"],
         repo_inspiration=["pgvector/pgvector"],
         resume_gap_filled="Demonstrates embeddings and vector search end-to-end.",
         key_features=["Semantic ranking", "Skill explainability", "Filterable search"],
         learning_outcomes=["Embeddings", "Vector DBs", "Ranking"],
         tags=["ML/AI", "Search", "Full-Stack"]),
    dict(title="GitOps Deployment Dashboard",
         subtitle="Visualize and promote deployments across environments",
         description="A control plane that reads GitOps state and lets you promote releases through environments with audit trails.",
         problem_statement="Promoting releases across envs is opaque and manual.",
         tech_stack=["TypeScript", "Go", "Kubernetes", "React"],
         architectures_used=["GitOps", "Control plane"],
         libraries_used=["client-go", "Recharts", "TanStack Query"],
         difficulty="Advanced",
         build_plan="## Phase 1\nRead desired vs live state.\n## Phase 2\nPromotion workflow with approvals.\n## Phase 3\nAudit trail + rollbacks.",
         ui_components=["Env pipeline view", "Diff viewer", "Approval modal"],
         repo_inspiration=["argoproj/argo-cd"],
         resume_gap_filled="Shows Kubernetes tooling and release engineering.",
         key_features=["Env promotion", "Drift detection", "Audited rollbacks"],
         learning_outcomes=["GitOps", "K8s API", "Release safety"],
         tags=["DevOps", "Full-Stack", "Developer Tools"]),
    dict(title="Personal Knowledge Graph",
         subtitle="Turn notes into a queryable graph",
         description="Parse markdown notes into entities and relationships and explore them as an interactive graph.",
         problem_statement="Flat notes hide the connections between ideas.",
         tech_stack=["Python", "FastAPI", "Neo4j", "React"],
         architectures_used=["Graph", "ETL"],
         libraries_used=["spaCy", "neo4j", "react-force-graph"],
         difficulty="Intermediate",
         build_plan="## Phase 1\nExtract entities from notes.\n## Phase 2\nBuild the graph in Neo4j.\n## Phase 3\nInteractive graph explorer.",
         ui_components=["Force graph", "Entity panel", "Search"],
         repo_inspiration=["neo4j/neo4j"],
         resume_gap_filled="Demonstrates NLP extraction and graph databases.",
         key_features=["Entity extraction", "Graph exploration", "Backlinks"],
         learning_outcomes=["Graph DBs", "NLP", "Visualization"],
         tags=["ML/AI", "Data Engineering", "Full-Stack"]),
]

added = 0
for p in MORE:
    if db.query(Project).filter(Project.title == p["title"]).first():
        continue
    db.add(Project(**p))
    added += 1
db.commit()
print(f"Added {added} projects; total now {db.query(Project).count()}.")
db.close()
