from database import SessionLocal, engine, Base
from models import Project

Base.metadata.create_all(bind=engine)

PROJECTS = [
    {
        "title": "AI Code Review Pipeline",
        "subtitle": "Automated PR analysis with ML-based bug prediction, style enforcement, and performance regression detection",
        "description": "A GitHub-integrated service that automatically reviews pull requests using a combination of static analysis, ML models, and LLM reasoning. The system scores each PR on code quality, security, performance, and test coverage, providing inline feedback and a dashboard for team-wide metrics.",
        "problem_statement": "Manual code reviews are inconsistent, time-consuming, and miss subtle bugs. Teams need automated, intelligent review that catches issues before they reach production.",
        "tech_stack": ["FastAPI", "React", "TypeScript", "PostgreSQL", "Docker", "Redis", "Celery"],
        "architectures_used": ["Microservices", "Event-driven architecture", "Webhook-based integration", "Background task processing"],
        "libraries_used": ["XGBoost", "OpenAI API", "SQLAlchemy", "Celery", "Pydantic", "Jinja2", "PyLint/Flake8 wrappers"],
        "difficulty": "Advanced",
        "estimated_time": "6-8 weeks",
        "ui_components": ["Interactive PR diff viewer with inline annotations", "Team dashboard with trend charts (Chart.js/Recharts)", "Configurable rule builder UI", "Historical analysis timeline", "Webhook status page"],
        "repo_inspiration": ["https://github.com/santifer/career-ops", "https://github.com/soxoj/maigret"],
        "resume_gap_filled": "Adds distributed microservices experience, event-driven architecture, and advanced ML (XGBoost) beyond the single FastAPI app. Shows DevOps integration with GitHub APIs and background job processing.",
        "key_features": ["ML-based bug risk scoring per commit", "Security vulnerability pattern detection", "Performance regression analysis", "Automated style enforcement with custom rules", "Team-wide quality metrics dashboard", "GitHub App integration with webhooks"],
        "learning_outcomes": ["Building and orchestrating microservices", "ML model training for code analysis", "GitHub App development & webhooks", "Background task processing with Celery", "Real-time UI updates with WebSockets"],
        "tags": ["ML/AI", "Developer Tools", "DevOps", "Microservices", "Code Quality"]
    },
    {
        "title": "Real-Time Collaborative Whiteboard",
        "subtitle": "Multi-user drawing app with WebSocket sync, vector graphics export, and session replay",
        "description": "A real-time collaborative whiteboard supporting multiple users simultaneously. Features include vector-based drawing tools, sticky notes, image imports, session recording/replay, and export to SVG/PNG/PDF. Built with FastAPI WebSockets for real-time sync and React for the canvas-based UI.",
        "problem_statement": "Remote teams lack lightweight, real-time visual collaboration tools that are self-hosted and privacy-focused, unlike SaaS offerings.",
        "tech_stack": ["FastAPI", "React", "TypeScript", "Redis", "PostgreSQL", "Docker", "Nginx"],
        "architectures_used": ["WebSocket real-time communication", "CRDT-based state synchronization", "Event sourcing for session replay", "Stateless backend with Redis pub/sub"],
        "libraries_used": ["FastAPI WebSockets", "Redis pub/sub", "roughjs", "perfect-freehand", "pdfkit", "Pydantic"],
        "difficulty": "Advanced",
        "estimated_time": "5-7 weeks",
        "ui_components": ["Infinite canvas with pan/zoom", "Toolbar with drawing, text, shape, and image tools", "Real-time cursor presence indicators", "Layer panel with reordering", "Session timeline scrubber for replay", "Export dialog (SVG/PNG/PDF)"],
        "repo_inspiration": ["https://github.com/soxoj/maigret", "https://github.com/coleam00/Archon"],
        "resume_gap_filled": "Demonstrates real-time systems expertise (WebSockets, CRDT), advanced frontend canvas work, and event sourcing — none of which appear on the current resume. Shows full-stack capability beyond CRUD APIs.",
        "key_features": ["Multi-user real-time co-drawing", "Session recording with playback", "Vector graphics export", "Undo/redo with branching history", "Image import and positioning", "Self-hosted with Docker"],
        "learning_outcomes": ["WebSocket lifecycle and connection management", "CRDT-based conflict-free data structures", "Canvas/SVG rendering optimization", "Event sourcing patterns", "Real-time communication at scale"],
        "tags": ["Real-Time", "Collaboration", "Full-Stack", "WebSockets", "UI/UX"]
    },
    {
        "title": "ML Model Registry & A/B Testing Platform",
        "subtitle": "Version-controlled model registry with shadow deployments, online evaluation, and automated rollback",
        "description": "A platform for data science teams to register, version, deploy, and A/B test ML models in production. Supports shadow scoring (deploy new model alongside current, compare results), gradual rollout, automated rollback on metric degradation, and a rich dashboard for comparing model performance.",
        "problem_statement": "Data science teams lack a unified system to version, deploy, and evaluate ML models in production. Shadow deployments and A/B testing are done ad-hoc, leading to risky rollouts and no performance regression tracking.",
        "tech_stack": ["FastAPI", "React", "TypeScript", "PostgreSQL", "Docker", "Redis", "MLflow"],
        "architectures_used": ["Multi-tenant SaaS architecture", "Shadow deployment pattern", "Canary release pipeline", "Event-driven metric collection"],
        "libraries_used": ["MLflow", "XGBoost", "LightGBM", "scikit-learn", "Prometheus client", "SQLAlchemy", "Pydantic"],
        "difficulty": "Advanced",
        "estimated_time": "7-9 weeks",
        "ui_components": ["Model registry browser with version diff view", "A/B test configuration wizard", "Real-time metric comparison charts", "Deployment pipeline visualization", "Alert configuration panel", "Shadow traffic analysis dashboard"],
        "repo_inspiration": ["https://github.com/santifer/career-ops", "https://github.com/coleam00/Archon"],
        "resume_gap_filled": "Extends Tejas's existing LightGBM experience into a full ML engineering platform. Adds MLOps, model lifecycle management, canary deployments, and A/B testing — critical skills for ML engineer roles.",
        "key_features": ["Model versioning with metadata", "Shadow deployment for risk-free testing", "A/B test assignment and tracking", "Automated rollback on metric degradation", "Performance comparison dashboards", "REST API for model inference"],
        "learning_outcomes": ["MLOps best practices and model lifecycle", "Canary and shadow deployment patterns", "Statistical A/B testing methodology", "Prometheus metric collection and alerting", "Multi-tenant SaaS architecture design"],
        "tags": ["ML/AI", "MLOps", "DevOps", "Full-Stack", "Data Engineering"]
    },
    {
        "title": "Distributed Task Orchestrator & Monitor",
        "subtitle": "Celery-based task queue with real-time monitoring, retry policies, DAG workflows, and Slack integration",
        "description": "A distributed task queue system built on Celery and Redis, with a rich monitoring dashboard. Supports DAG-based workflow definitions, configurable retry policies, task scheduling, worker auto-scaling, and Slack/email notifications. Provides real-time task tracing and performance analytics.",
        "problem_statement": "Background job failures in distributed systems are hard to debug without centralized tracing, retry policies, and real-time visibility into worker health and queue depths.",
        "tech_stack": ["FastAPI", "React", "TypeScript", "Redis", "PostgreSQL", "Docker", "Celery", "Flower"],
        "architectures_used": ["Distributed task queue", "Producer-consumer pattern", "DAG execution engine", "Event-driven monitoring"],
        "libraries_used": ["Celery", "Redis-py", "SQLAlchemy", "WebSockets", "Recharts", "Pydantic", "APScheduler"],
        "difficulty": "Advanced",
        "estimated_time": "5-7 weeks",
        "ui_components": ["Live task stream with filtering", "DAG workflow visual editor", "Worker pool dashboard with metrics", "Task timeline and trace viewer", "Retry policy configuration panel", "Alert/notification rule builder"],
        "repo_inspiration": ["https://github.com/coleam00/Archon", "https://github.com/santifer/career-ops"],
        "resume_gap_filled": "Showcases distributed systems architecture, background processing, and real-time monitoring — major gaps in the current resume. Essential for backend/infrastructure roles.",
        "key_features": ["DAG-based workflow definitions (YAML)", "Real-time task tracing with spans", "Intelligent retry with exponential backoff", "Worker auto-scaling based on queue depth", "Slack/email/webhook notifications", "Task scheduling and cron support"],
        "learning_outcomes": ["Distributed task queue internals", "DAG execution engine design", "Real-time monitoring systems", "Graceful failure handling patterns", "Horizontal worker scaling strategies"],
        "tags": ["Distributed Systems", "Backend", "DevOps", "Real-Time", "Infrastructure"]
    },
    {
        "title": "Personal Finance Intelligence Engine",
        "subtitle": "AI-powered financial aggregator with spending forecasts, anomaly detection, and goal tracking",
        "description": "A personal finance platform that connects to bank accounts via Plaid, categorizes transactions using ML, predicts future spending patterns, detects anomalies (fraud, unusual subscriptions), and provides an interactive dashboard for budgeting and goal tracking.",
        "problem_statement": "Personal finance tools either lack ML-powered insights or require manual categorization. Users want automated spending analysis, predictive budgeting, and anomaly alerts without sharing data with third-party aggregators.",
        "tech_stack": ["FastAPI", "React", "TypeScript", "PostgreSQL", "Docker", "Redis"],
        "architectures_used": ["Hexagonal architecture", "Third-party API integration", "Batch ML inference pipeline", "Event-driven anomaly detection"],
        "libraries_used": ["LightGBM", "XGBoost", "Plaid API", "SQLAlchemy", "Pydantic", "Recharts", "date-fns"],
        "difficulty": "Intermediate",
        "estimated_time": "5-7 weeks",
        "ui_components": ["Dashboard with spending breakdown (pie/bar charts)", "Transaction feed with ML-based categorization", "Budget setting with progress rings", "Anomaly alert timeline", "Forecast projection chart", "Goal tracking with milestone visualization"],
        "repo_inspiration": ["https://github.com/santifer/career-ops", "https://github.com/soxoj/maigret"],
        "resume_gap_filled": "Strengthens the ML + finance angle from Prophecy project with a more polished product. Adds third-party API integration (Plaid), unsupervised anomaly detection, and advanced data visualization.",
        "key_features": ["Plaid API transaction sync", "ML-based transaction categorization", "Spending forecast with confidence intervals", "Anomaly and fraud detection", "Multi-account aggregation", "Savings goal tracking with projections"],
        "learning_outcomes": ["Third-party financial API integration", "Time series forecasting with ML", "Anomaly detection techniques", "Data pipeline design for ML inference", "Interactive financial dashboards"],
        "tags": ["ML/AI", "FinTech", "Full-Stack", "Data Visualization", "Personal Finance"]
    },
    {
        "title": "Semantic Document Search & QA Platform",
        "subtitle": "RAG-powered enterprise search across documents with citation-backed answers, source management, and access control",
        "description": "An enterprise document search platform using Retrieval-Augmented Generation (RAG). Users upload documents (PDF, DOCX, HTML), the system chunks and indexes them with embeddings, then provides natural language Q&A with cited sources. Includes user access control, document versioning, and sharing.",
        "problem_statement": "Enterprise knowledge is trapped in siloed documents. Traditional keyword search fails to answer natural language questions, and existing RAG solutions are complex to deploy and lack access control.",
        "tech_stack": ["FastAPI", "React", "TypeScript", "PostgreSQL", "Docker", "ChromaDB", "Redis"],
        "architectures_used": ["RAG (Retrieval-Augmented Generation)", "Embedding-based vector search", "Document pipeline with chunking", "Multi-tenant data isolation"],
        "libraries_used": ["LangChain", "OpenAI API / Gemini API", "ChromaDB", "pgvector", "Unstructured (document parsing)", "SQLAlchemy"],
        "difficulty": "Intermediate",
        "estimated_time": "5-7 weeks",
        "ui_components": ["Document upload and management UI", "Chat interface with source citation cards", "Search results with relevance highlighting", "Collection/tag browser sidebar", "Document preview with embedded viewer", "Share and permission settings panel"],
        "repo_inspiration": ["https://github.com/coleam00/Archon", "https://github.com/soxoj/maigret"],
        "resume_gap_filled": "Adds LLM/RAG experience, vector databases, and LangChain — currently missing from resume. Enterprise search is a high-demand skill. Shows ability to build AI-powered products beyond basic ML prediction.",
        "key_features": ["Multi-format document parsing (PDF/DOCX/HTML)", "Semantic search with hybrid (vector + keyword)", "Citation-backed Q&A responses", "Document collections and tagging", "User access control and sharing", "Batch document ingestion pipeline"],
        "learning_outcomes": ["RAG architecture and retrieval strategies", "Vector database design and tuning", "LangChain for LLM application development", "Document chunking strategies", "Hybrid search (vector + keyword) implementation"],
        "tags": ["ML/AI", "LLM", "RAG", "Full-Stack", "Search"]
    },
    {
        "title": "IoT Sensor Data Lake & Alerting System",
        "subtitle": "Time-series ingestion pipeline for IoT sensors with real-time dashboards, ML-based anomaly detection, and SMS alerts",
        "description": "A scalable IoT data platform that ingests sensor data via MQTT/HTTP, stores in TimescaleDB, processes with streaming analytics, detects anomalies using ML (Isolation Forest, LSTM), and triggers alerts through SMS/email/webhook. Includes a real-time operational dashboard.",
        "problem_statement": "IoT deployments generate massive time-series data that is difficult to store, query, and monitor in real time. Off-the-shelf solutions are expensive and don't support custom ML-based anomaly detection.",
        "tech_stack": ["FastAPI", "React", "TypeScript", "TimescaleDB", "Docker", "MQTT", "Redis"],
        "architectures_used": ["Event-driven ingestion pipeline", "Time-series data modeling", "Streaming analytics with windowing", "CQRS (read/write separation)"],
        "libraries_used": ["scikit-learn (Isolation Forest)", "TensorFlow/Keras (LSTM)", "psycopg2", "paho-mqtt", "WebSockets", "Recharts", "Twilio API"],
        "difficulty": "Advanced",
        "estimated_time": "6-8 weeks",
        "ui_components": ["Real-time sensor dashboard with gauges", "Time-series chart explorer with zoom", "Alert rule builder (threshold/ML)", "Incident timeline view", "Device registry and management panel", "Live map of sensor locations"],
        "repo_inspiration": ["https://github.com/santifer/career-ops", "https://github.com/coleam00/Archon"],
        "resume_gap_filled": "Adds IoT/embedded systems experience, time-series databases, streaming analytics, and anomaly detection — completely new territory that distinguishes Tejas from typical SWE candidates.",
        "key_features": ["MQTT sensor data ingestion", "Time-series compression and retention policies", "Real-time dashboard with sub-second updates", "ML-based anomaly detection (Isolation Forest + LSTM)", "Multi-channel alerting (SMS/email/webhook)", "Device registry and health monitoring"],
        "learning_outcomes": ["Time-series database design (TimescaleDB)", "MQTT protocol and IoT communication", "Streaming analytics and windowing", "Anomaly detection for time-series data", "Real-time data pipeline architecture"],
        "tags": ["IoT", "Real-Time", "ML/AI", "Data Engineering", "Infrastructure"]
    },
    {
        "title": "API Gateway & Developer Portal",
        "subtitle": "Self-service API gateway with rate limiting, key management, usage analytics, and interactive API documentation",
        "description": "A full-featured API gateway that sits in front of microservices, handling authentication, rate limiting, API key management, request/response transformation, and usage analytics. Includes a developer portal where users can sign up, get keys, browse APIs, test endpoints, and view usage.",
        "problem_statement": "Microservice teams need a unified API layer for authentication, rate limiting, and developer onboarding. Existing API gateways are either too heavy (Kong) or too cloud-specific (AWS API Gateway).",
        "tech_stack": ["FastAPI", "React", "TypeScript", "PostgreSQL", "Redis", "Docker", "Traefik"],
        "architectures_used": ["API Gateway pattern", "Reverse proxy with middleware chain", "Token-based authentication", "Usage-based billing tier model"],
        "libraries_used": ["httpx", "SQLAlchemy", "Pydantic", "Recharts", "react-syntax-highlighter", "Swagger/OpenAPI", "Redis-py"],
        "difficulty": "Intermediate",
        "estimated_time": "5-7 weeks",
        "ui_components": ["Interactive API explorer with live testing", "API key management dashboard", "Usage analytics with time-series charts", "Rate limit configuration panel", "Developer signup and onboarding flow", "Webhook subscription manager"],
        "repo_inspiration": ["https://github.com/santifer/career-ops", "https://github.com/coleam00/Archon"],
        "resume_gap_filled": "Demonstrates API design expertise, middleware architecture, and developer experience — critical for platform engineering roles. Rate limiting and key management systems are directly applicable to cloud platform roles.",
        "key_features": ["API key generation and rotation", "Configurable rate limiting (per-key, per-endpoint)", "Usage analytics and billing reports", "Interactive API documentation", "Request/response transformation", "Webhook event delivery system"],
        "learning_outcomes": ["API Gateway architecture and middleware chain", "Rate limiting algorithms (token bucket, leaky bucket)", "Developer portal UX patterns", "API monetization and tiered access", "Reverse proxy internals"],
        "tags": ["Backend", "API", "DevOps", "Platform Engineering", "Full-Stack"]
    },
    {
        "title": "Social Media OSINT Analyzer",
        "subtitle": "Multi-platform social media search and analysis tool with graph-based relationship mapping and PDF reporting",
        "description": "An investigation platform that searches for usernames across 100+ social platforms, extracts profile information, maps relationships between accounts, analyzes posting patterns, and generates professional PDF/HTML reports. Inspired by maigret but with a modern web UI and graph database backend.",
        "problem_statement": "Investigators need to find and correlate user identities across dozens of social platforms. Existing tools either lack a web UI, have limited platform coverage, or don't visualize relationship graphs.",
        "tech_stack": ["FastAPI", "React", "TypeScript", "Neo4j", "PostgreSQL", "Docker", "Redis"],
        "architectures_used": ["Graph database model", "Async web scraping pipeline", "Plugin-based site adapters", "Report generation pipeline"],
        "libraries_used": ["httpx (async)", "BeautifulSoup4", "Neo4j Python driver", "Playwright", "Jinja2", "pdfkit", "NetworkX", "D3.js"],
        "difficulty": "Advanced",
        "estimated_time": "6-8 weeks",
        "ui_components": ["Interactive graph visualization (D3.js force-directed)", "Search dashboard with multi-username input", "Profile detail panel with extracted data", "Relationship explorer with expand/collapse", "Report preview and download page", "Tag and case management sidebar"],
        "repo_inspiration": ["https://github.com/soxoj/maigret", "https://github.com/santifer/career-ops"],
        "resume_gap_filled": "Adds async web scraping, graph databases (Neo4j), OSINT domain knowledge, and professional reporting — completely new skill areas. Shows C++-level performance thinking applied to Python async scraping.",
        "key_features": ["Username search across 100+ platforms", "Profile data extraction and enrichment", "Relationship graph mapping between accounts", "Temporal posting pattern analysis", "PDF/HTML/CSV report generation", "Case-based investigation management"],
        "learning_outcomes": ["Graph database modeling with Neo4j", "Async web scraping at scale", "Plugin/adapter architecture patterns", "Professional report generation", "OSINT methodology and ethical considerations"],
        "tags": ["OSINT", "Data Engineering", "Graph Database", "Async", "Security"]
    },
    {
        "title": "Multi-Agent AI Workflow Engine",
        "subtitle": "Define, execute, and monitor multi-step AI agent workflows with human-in-the-loop gates and parallel execution",
        "description": "A workflow engine for orchestrating multiple AI agents. Define DAG-based workflows in YAML where each node is an agent task (code generation, research, review, etc.). Supports parallel execution, human approval gates, loop-until nodes, and a web dashboard for monitoring. Inspired by Archon's workflow model.",
        "problem_statement": "AI coding agents produce inconsistent results because they lack structured, repeatable workflows. Teams need deterministic multi-agent pipelines with human oversight and parallel execution.",
        "tech_stack": ["FastAPI", "React", "TypeScript", "PostgreSQL", "Docker", "Redis", "Celery"],
        "architectures_used": ["DAG-based workflow execution", "Multi-agent orchestration", "Human-in-the-loop pattern", "Event-driven state machine"],
        "libraries_used": ["LangChain", "OpenAI API / Gemini API", "Celery", "SQLAlchemy", "React Flow", "Pydantic", "NetworkX"],
        "difficulty": "Advanced",
        "estimated_time": "8-10 weeks",
        "ui_components": ["Visual workflow builder (drag-and-drop DAG editor)", "Real-time execution progress view", "Agent output inspection panel", "Human approval request interface", "Workflow template library", "Execution history with diff comparison"],
        "repo_inspiration": ["https://github.com/coleam00/Archon", "https://github.com/santifer/career-ops"],
        "resume_gap_filled": "Shows AI agent orchestration, workflow engine design, and DAG execution — cutting-edge skills that directly align with the Archon-style projects employers are excited about. Positions Tejas at the forefront of AI engineering.",
        "key_features": ["YAML-based workflow definitions", "Parallel agent execution with dependency resolution", "Human-in-the-loop approval gates", "Loop-until nodes with condition evaluation", "Real-time execution monitoring", "Template system for reusable workflows"],
        "learning_outcomes": ["DAG execution engine design", "Multi-agent orchestration patterns", "Human-in-the-loop system design", "State machine implementation", "Visual workflow editor development"],
        "tags": ["ML/AI", "AI Agents", "Workflow", "Full-Stack", "Automation"]
    },
    {
        "title": "Infrastructure Cost Optimizer",
        "subtitle": "Cloud cost analysis and optimization platform with resource right-sizing, usage forecasting, and automated recommendations",
        "description": "A platform that connects to AWS/Azure/GCP accounts, analyzes resource usage patterns, identifies cost-saving opportunities (right-sizing, reserved instances, spot instances), forecasts future costs using ML, and generates actionable optimization reports with estimated savings.",
        "problem_statement": "Cloud costs spiral out of control without visibility into resource utilization. Teams need automated right-sizing recommendations and cost forecasting to optimize spending across multi-cloud environments.",
        "tech_stack": ["FastAPI", "React", "TypeScript", "PostgreSQL", "Docker", "Redis", "Celery"],
        "architectures_used": ["Multi-cloud provider abstraction", "Batch data collection pipeline", "ML forecasting pipeline", "Recommendation engine"],
        "libraries_used": ["boto3", "azure-mgmt-costmanagement", "XGBoost", "scikit-learn", "Celery", "Recharts", "SQLAlchemy"],
        "difficulty": "Intermediate",
        "estimated_time": "5-7 weeks",
        "ui_components": ["Cost breakdown dashboard with treemap", "Resource inventory with utilization heatmap", "Recommendation cards with savings estimates", "Forecast chart with what-if scenarios", "Budget alert configuration panel", "Exportable report generator"],
        "repo_inspiration": ["https://github.com/santifer/career-ops", "https://github.com/coleam00/Archon"],
        "resume_gap_filled": "Leverages Tejas's AWS research background (Bytepoint Consulting) into a tangible engineering product. Adds multi-cloud experience, cost optimization expertise, and ML forecasting — directly applicable to cloud/SRE roles.",
        "key_features": ["Multi-cloud account connection (AWS/Azure/GCP)", "Resource right-sizing recommendations", "Reserved instance purchase optimizer", "ML-based cost forecasting", "Budget tracking with alerts", "Optimization report export (PDF/CSV)"],
        "learning_outcomes": ["Cloud provider APIs and cost models", "ML for time-series forecasting", "Multi-cloud abstraction layer design", "Cost optimization strategies", "FinOps best practices"],
        "tags": ["Cloud", "DevOps", "ML/AI", "FinOps", "Infrastructure"]
    },
    {
        "title": "Real-Time Dashboard Builder",
        "subtitle": "Drag-and-drop dashboard constructor with custom widgets, SQL data sources, and auto-refresh",
        "description": "A self-service dashboard builder where users connect data sources (PostgreSQL, REST APIs, CSV), build interactive visualizations with a drag-and-drop editor, set up auto-refresh schedules, and share dashboards with team members. Features a library of widget types (charts, tables, gauges, maps).",
        "problem_statement": "Teams need custom dashboards that combine data from multiple sources, but existing solutions (Grafana, Metabase) require complex setup or don't support drag-and-drop widget configuration.",
        "tech_stack": ["FastAPI", "React", "TypeScript", "PostgreSQL", "Docker", "Redis", "WebSockets"],
        "architectures_used": ["Micro-frontend widget architecture", "WebSocket-driven live updates", "Multi-tenant data isolation", "Plugin system for custom widgets"],
        "libraries_used": ["react-grid-layout", "Recharts", "SQLAlchemy", "Pydantic", "Pandas", "WebSockets", "react-query"],
        "difficulty": "Intermediate",
        "estimated_time": "6-8 weeks",
        "ui_components": ["Drag-and-drop grid canvas", "Widget configuration sidebar", "SQL query editor with autocomplete", "Data source connection wizard", "Dashboard template gallery", "Share and permission settings"],
        "repo_inspiration": ["https://github.com/santifer/career-ops", "https://github.com/coleam00/Archon"],
        "resume_gap_filled": "Demonstrates advanced frontend skills (drag-and-drop, grid layouts, widget architecture) beyond basic React. Shows data connectivity and visualization expertise — highly valued in data/platform engineering roles.",
        "key_features": ["Drag-and-drop dashboard layout editor", "SQL and REST API data sources", "Auto-refresh with configurable intervals", "Widget library (charts, tables, gauges, maps)", "Dashboard template system", "Team sharing with role-based access"],
        "learning_outcomes": ["Drag-and-drop UI architecture", "Micro-frontend and widget plugin patterns", "Real-time data refresh strategies", "SQL query builder implementation", "Dashboard UX design principles"],
        "tags": ["Data Visualization", "Frontend", "Full-Stack", "Real-Time", "Analytics"]
    },
    {
        "title": "AI-Powered Meeting Minutes & Action Tracker",
        "subtitle": "Speech-to-text meeting transcription with speaker diarization, action item extraction, and calendar integration",
        "description": "A meeting intelligence platform that joins video calls, generates real-time transcripts with speaker identification, uses LLMs to extract action items, decisions, and key discussion points, and automatically creates calendar events with summaries. Includes a searchable meeting archive.",
        "problem_statement": "Meeting notes are manually taken, incomplete, and action items get lost. Teams need automated transcription with speaker identification and structured extraction of decisions and follow-ups.",
        "tech_stack": ["FastAPI", "React", "TypeScript", "PostgreSQL", "Docker", "Redis", "Celery"],
        "architectures_used": ["Event-driven processing pipeline", "Async audio streaming", "LLM-powered extraction pipeline", "Calendar API integration"],
        "libraries_used": ["OpenAI Whisper", "LangChain", "Google Calendar API / Outlook API", "SQLAlchemy", "Celery", "WebSockets", "Pydantic"],
        "difficulty": "Advanced",
        "estimated_time": "6-8 weeks",
        "ui_components": ["Real-time transcript view with speaker colors", "Action item board with assignee tracking", "Meeting timeline with topic markers", "Searchable meeting archive", "Calendar integration settings", "Email summary delivery configuration"],
        "repo_inspiration": ["https://github.com/santifer/career-ops", "https://github.com/coleam00/Archon"],
        "resume_gap_filled": "Adds speech-to-text/Audio AI experience, real-time streaming, and calendar API integration. Shows ability to work with unstructured data (audio) and extract structured insights using LLMs.",
        "key_features": ["Real-time speech-to-text transcription", "Speaker diarization (who said what)", "LLM-based action item extraction", "Automatic calendar event creation", "Email summary delivery", "Searchable meeting archive with full-text search"],
        "learning_outcomes": ["Audio processing and streaming", "Speaker diarization techniques", "LLM prompt engineering for extraction", "Calendar API integration patterns", "Real-time collaborative editing"],
        "tags": ["ML/AI", "LLM", "Real-Time", "Productivity", "Full-Stack"]
    },
    {
        "title": "ML Data Drift Monitor & Alert System",
        "subtitle": "Production ML model monitoring with data drift detection, concept drift alerts, and automated retraining triggers",
        "description": "A monitoring platform for production ML models that continuously tracks input data distributions, detects drift (data drift, concept drift, label drift), generates alerts, and can trigger automated retraining pipelines. Includes a dashboard for comparing distributions and a model health score.",
        "problem_statement": "ML models degrade in production as data distributions shift over time. Teams need automated drift detection and alerting to maintain model performance without manual dashboard staring.",
        "tech_stack": ["FastAPI", "React", "TypeScript", "PostgreSQL", "Docker", "Redis", "Prometheus"],
        "architectures_used": ["Streaming data analysis pipeline", "Statistical test automation", "Model health scoring system", "Automated retraining trigger"],
        "libraries_used": ["Evidently AI", "scikit-learn", "XGBoost", "LightGBM", "Prometheus client", "SQLAlchemy", "Recharts", "Pandas"],
        "difficulty": "Advanced",
        "estimated_time": "5-7 weeks",
        "ui_components": ["Model health score dashboard", "Distribution comparison charts (drift visualizer)", "Alert timeline with severity indicators", "Feature-level drift detail panels", "Automated retraining configuration", "Model performance over time charts"],
        "repo_inspiration": ["https://github.com/santifer/career-ops", "https://github.com/coleam00/Archon"],
        "resume_gap_filled": "Builds on Tejas's LightGBM/ML experience into MLOps monitoring — a critical skill gap. Model monitoring and drift detection are top requirements for ML engineer roles. Shows production ML thinking beyond just building models.",
        "key_features": ["Data drift detection (PSI, KS test, Jensen-Shannon)", "Concept drift detection", "Model performance tracking over time", "Automated alerting with severity levels", "Retraining pipeline trigger", "Drift report generation"],
        "learning_outcomes": ["ML model monitoring in production", "Statistical drift detection methods", "Evidently AI library for drift analysis", "Prometheus metrics for ML systems", "Automated ML pipeline design"],
        "tags": ["ML/AI", "MLOps", "Data Engineering", "Monitoring", "DevOps"]
    },
    {
        "title": "Competitive Programming Arena",
        "subtitle": "Online judge platform with real-time code execution, test case validation, leaderboards, and contest management",
        "description": "A competitive programming platform where users solve algorithmic challenges with real-time code execution in sandboxed environments. Supports multiple languages (Python, Java, C++, Swift), automated test case validation, contest scheduling, rating system, and a rich problem editor.",
        "problem_statement": "Aspiring competitive programmers lack a self-hosted platform with sandboxed multi-language execution, contest management, and rating systems similar to LeetCode or Codeforces.",
        "tech_stack": ["FastAPI", "React", "TypeScript", "PostgreSQL", "Docker", "Redis", "Celery"],
        "architectures_used": ["Sandboxed code execution", "Event-driven submission pipeline", "Elo/Glicko rating system", "Real-time leaderboard updates"],
        "libraries_used": ["Docker SDK (spawn containers)", "Celery", "WebSockets", "Monaco Editor", "SQLAlchemy", "Pydantic", "Redis-py"],
        "difficulty": "Advanced",
        "estimated_time": "8-10 weeks",
        "ui_components": ["Code editor with Monaco (syntax highlighting, themes)", "Test case result panel with diff view", "Real-time contest leaderboard", "Problem statement viewer with markdown", "Submission history with status timeline", "Rating progression chart"],
        "repo_inspiration": ["https://github.com/soxoj/maigret", "https://github.com/coleam00/Archon"],
        "resume_gap_filled": "Leverages Tejas's C++, Java, Python, Swift knowledge into a unified platform. Shows sandboxed execution, rating systems, and real-time competitive features. Demonstrates full-stack depth across multiple languages.",
        "key_features": ["Multi-language code execution (Python, Java, C++, Swift)", "Docker-based sandboxed execution environment", "Custom test case validation with diff output", "Contest management with scheduling", "Elo/Glicko player rating system", "Real-time leaderboard with WebSockets"],
        "learning_outcomes": ["Sandboxed code execution security", "Docker container lifecycle management", "Rating system mathematics (Elo/Glicko)", "Real-time competitive event systems", "Online judge architecture patterns"],
        "tags": ["Full-Stack", "Real-Time", "Developer Tools", "Education", "Multi-Language"]
    },
    {
        "title": "Hackathon Hub — Event & Project Manager",
        "subtitle": "Full hackathon lifecycle platform: event management, team formation, project submission, judging, and sponsor tracking",
        "description": "A complete hackathon management platform covering the entire event lifecycle. Features include event creation with scheduling, team formation with skill matching, project submission with repo linking, multi-criteria judging with scoring rubrics, sponsor management, and real-time live leaderboards.",
        "problem_statement": "Hackathon organizers juggle spreadsheets, multiple tools, and manual processes for team formation, project submissions, and judging. A unified platform is needed to manage the entire lifecycle.",
        "tech_stack": ["FastAPI", "React", "TypeScript", "PostgreSQL", "Docker", "Redis", "WebSockets"],
        "architectures_used": ["Modular event lifecycle state machine", "Multi-tenant organization model", "Real-time scoring aggregation", "Plugin-based judging criteria"],
        "libraries_used": ["SQLAlchemy", "Pydantic", "WebSockets", "Recharts", "react-beautiful-dnd", "date-fns", "Pandas (export)"],
        "difficulty": "Intermediate",
        "estimated_time": "5-7 weeks",
        "ui_components": ["Event creation wizard with timeline", "Team formation board with skill tags", "Project submission portal with GitHub integration", "Judge scorecard interface with rubrics", "Live leaderboard with WebSocket updates", "Sponsor management dashboard"],
        "repo_inspiration": ["https://github.com/santifer/career-ops", "https://github.com/coleam00/Archon"],
        "resume_gap_filled": "Perfectly leverages Tejas's DECA/Design Society leadership experience into an engineering product. Shows event systems expertise, real-time scoring, and organizational workflow management — unique angle most SWE resumes lack.",
        "key_features": ["Hackathon lifecycle management (create to archive)", "Skill-based team formation matching", "GitHub integration for project submission", "Customizable judging rubrics", "Real-time scoring and leaderboard", "Sponsor tier management"],
        "learning_outcomes": ["Event lifecycle state machine design", "Team matching algorithm implementation", "Real-time aggregation and broadcasting", "Multi-criteria judging system design", "Export and reporting pipeline"],
        "tags": ["Full-Stack", "Real-Time", "Event Management", "Community", "Productivity"]
    },
    {
        "title": "Personal Knowledge Graph & Second Brain",
        "subtitle": "Note-taking with graph-based connections, semantic search, auto-tagging, and spaced repetition flashcards",
        "description": "A personal knowledge management system that stores notes as nodes in a graph database, automatically suggests connections between related notes using embeddings, provides semantic search, and generates spaced repetition flashcards from notes. Features a rich markdown editor and graph visualization.",
        "problem_statement": "Traditional note-taking apps lack intelligent connections between ideas. Users want a second brain that surfaces related notes, suggests links, and reinforces learning through spaced repetition.",
        "tech_stack": ["FastAPI", "React", "TypeScript", "Neo4j", "Docker", "Redis", "PostgreSQL"],
        "architectures_used": ["Graph database for knowledge representation", "Embedding-based similarity search", "Event-driven suggestion pipeline", "Spaced repetition algorithm"],
        "libraries_used": ["Neo4j Python driver", "OpenAI/Gemini embeddings", "react-force-graph-2d", "TipTap editor", "SQLAlchemy", "Pydantic"],
        "difficulty": "Intermediate",
        "estimated_time": "5-7 weeks",
        "ui_components": ["Interactive knowledge graph visualization", "Rich markdown editor (TipTap)", "Note detail panel with backlinks", "Auto-suggestion sidebar", "Flashcard review interface (spaced repetition)", "Tag and filter sidebar"],
        "repo_inspiration": ["https://github.com/coleam00/Archon", "https://github.com/soxoj/maigret"],
        "resume_gap_filled": "Second Neo4j project reinforcing graph database skills. Adds rich text editing, embedding-based recommendations, and spaced repetition algorithms. Shows ability to build complex, interconnected data models.",
        "key_features": ["Graph-based note organization", "AI-powered connection suggestions", "Semantic search across notes", "Auto-generated spaced repetition flashcards", "Markdown editing with live preview", "Backlink and reference tracking"],
        "learning_outcomes": ["Graph database modeling for knowledge", "Text embedding and similarity search", "Spaced repetition algorithm (SM-2)", "Rich text editor integration", "Graph visualization with force-directed layouts"],
        "tags": ["Graph Database", "ML/AI", "Productivity", "Full-Stack", "Knowledge Management"]
    },
    {
        "title": "API Security Fuzzer & Vulnerability Scanner",
        "subtitle": "Automated API security testing with intelligent fuzzing, OWASP top 10 detection, and CI/CD integration",
        "description": "A security testing tool that takes an OpenAPI spec, generates intelligent fuzz payloads, tests endpoints for OWASP Top 10 vulnerabilities (injection, broken auth, excessive data exposure, etc.), and produces detailed security reports. Integrates with CI/CD pipelines via CLI and GitHub Actions.",
        "problem_statement": "API security testing is often manual or requires expensive commercial scanners. Teams need an open-source, automated fuzzer that integrates directly into their CI/CD pipeline.",
        "tech_stack": ["FastAPI", "React", "TypeScript", "PostgreSQL", "Docker", "Redis", "Celery"],
        "architectures_used": ["Plugin-based payload generator", "CI/CD pipeline integration", "Parallel security testing engine", "Report generation pipeline"],
        "libraries_used": ["httpx", "Pydantic", "Jinja2", "Celery", "Recharts", "react-syntax-highlighter", "OpenAPI parser"],
        "difficulty": "Advanced",
        "estimated_time": "6-8 weeks",
        "ui_components": ["API endpoint explorer with security scores", "Fuzz testing configuration wizard", "Vulnerability detail panel with remediation steps", "CI/CD integration setup guide", "Security trend dashboard over time", "Report preview and export (PDF/HTML)"],
        "repo_inspiration": ["https://github.com/soxoj/maigret", "https://github.com/santifer/career-ops"],
        "resume_gap_filled": "Adds security engineering expertise — a high-demand skill area. Shows CI/CD integration, fuzz testing methodologies, and OWASP knowledge. Security engineers are consistently in short supply.",
        "key_features": ["OpenAPI spec parsing and endpoint discovery", "Intelligent fuzz payload generation", "OWASP Top 10 vulnerability detection", "Parallel async security testing", "CI/CD integration (GitHub Actions, CLI)", "Detailed security reports with remediation"],
        "learning_outcomes": ["API security testing methodologies", "Fuzz testing and payload generation", "OWASP Top 10 vulnerability patterns", "CI/CD pipeline integration patterns", "Security report generation standards"],
        "tags": ["Security", "API", "DevOps", "Testing", "Automation"]
    },
]

def seed():
    db = SessionLocal()
    existing = db.query(Project).count()
    if existing > 0:
        print(f"Database already has {existing} projects. Skipping seed.")
        db.close()
        return

    for p in PROJECTS:
        db.add(Project(**p))
    db.commit()
    db.close()
    print(f"Seeded {len(PROJECTS)} projects.")

if __name__ == "__main__":
    seed()
